config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'members' }

  get 'welcome/index'

  resources :blogs
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user

    has_one_attached :blog_pics
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates_confirmation_of :password
         validates_presence_of :password_confirmation, :on => :create
         validates_uniqueness_of :email
         validates :username, presence: true
         validates :username, uniqueness: true, if: -> { self.username.present? }
         validates_uniqueness_of :username, case_sensitive: false
         validates_presence_of :username 

  has_many :blogs, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :avatar, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :avatar, :email, :password, :current_password)}
         end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

    def index
        @blogs = Blog.all
      end

    def show
        @blog = Blog.find(params[:id])
    end

    def new
        #@blog = Blog.new
        #@blog = current_user.blogs.build
        if current_user
          current_user.blogs.build
        else
          redirect_to root_path, alert: 'Login to create a new blog'
        end
    end

    def edit
      @blog = Blog.find(params[:id])
      if @blog.user_id != current_user.id
        redirect_to blogs_path
      end
    end

    def create
        #@blog = Blog.new(bloge)
        @blog = current_user.blogs.build(bloge)
 
        @blog.save
        redirect_to @blog
    end

    def update
        @blog = Blog.find(params[:id])
       
        if @blog.update(bloge)
          redirect_to @blog
        else
          render 'edit'
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
     
        redirect_to root_path
    end

    private
        def bloge
            params.require(:blog).permit(:title, :text, :blog_pics)
        end
end

app/controllers/members_controller.rb
class MembersController < Devise::RegistrationsController

    def create
        @user = User.new(user)

        if @user.save
            redirect_to new_user_session_path
        else
            flash[:error] = @user.errors
            redirect_to new_user_registration_path
        end

        

    end

    private
    def user
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @blogs = Blog.all

    if current_user
      @user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      html = <<-HTML
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
         #{pluralize(resource.errors.count, "error")} must be fixed
        </strong>
        #{messages}
      </div>
      HTML
  
      html.html_safe
    end
  end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/edit.html.erb
<style>
.login{
  min-height: 100vh;
}

section {
  background-image: linear-gradient(to bottom right, #FFEFBA, #FFFFFF);
  height: 100vh;
}

.bg{
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  padding: 2em;
  margin-top: 40%;
}

label, h3{
  color: black;
}

.btn-login {
  background-image: linear-gradient(to bottom right, #ffa751, #ffe259);
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
  border-radius: 2rem;
  color: white;
}
.btn-login:hover {
  background-image: linear-gradient(to bottom right, #ffe259, #ffa751);
  color: white;
}

@media (max-width: 768px){
  .bg{
    background-color: rgba(255, 255, 255, 0.7);
  }

    section img{
      display: none;
  }
}

</style>

<section>
  <%= image_tag 'bled.png', style: 'position: absolute; bottom: 0; right: 0;' %>
  
  <div class ="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="bg">
          <center><h3 class="login-heading mb-4">Blog Editor</h3></center>
          <%= form_with(model: @blog, local: true) do |form| %>


            <% if @blog.errors.any? %>
              <div id="error_explanation">
                <h2>
                  <%= pluralize(@blog.errors.count, "error") %> prohibited
                  this blog from being saved:
                </h2>
                <ul>
                  <% @blog.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>


            <div class="form-label-group">
              <label for="inputEmail">Blog title</label>
              <%= form.text_field :title, class: 'form-control'%>
            </div>

            <div class="form-label-group">
              <label for="inputPassword">Blog content</label>
              <%= form.text_area :text, class: 'form-control',  required: true %>
            </div>

            <br>

            <%= form.submit "Update blog", class: 'btn btn-lg btn-block btn-login text-uppercase font-weight-bold mb-2' %>

            <div class="text-center">
            <%= link_to 'BACK', blog_path, class: 'large', style: 'color: black; font-weight: 600; text-decoration: underline' %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</section>   
















<!-- <h1>Blog Editor</h1>
 
<%= form_with(model: @blog, local: true) do |form| %>
 
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

  <%= link_to 'Back', blog_path %>
 
<% end %> -->
 

app/views/blogs/index.html.erb
<h1>BLOGS</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.text %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      <td><%= link_to 'Delete', blog_path(blog),
      method: :delete,
      data: { confirm: 'Are you sure? Once you delete you can no longer retrieve your blog' } %></td>
    </tr>
  <% end %>
</table>

app/views/blogs/new.html.erb
<style>
.login{
  min-height: 100vh;
}

section {
  background-image: linear-gradient(to bottom right, #FFEFBA, #FFFFFF);
  height: 100vh;
}

.bg{
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  padding: 2em;
  margin-top: 40%;
}

label, h3{
  color: black;
}

.btn-login {
  background-image: linear-gradient(to bottom right, #ffa751, #ffe259);
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
  border-radius: 2rem;
  color: white;
}
.btn-login:hover {
  background-image: linear-gradient(to bottom right, #ffe259, #ffa751);
  color: white;
}

@media (max-width: 768px){
    .bg{
        background-color: rgba(255, 255, 255, 0.7);
      }
    
        section img{
          display: none;
      }
}

</style>



<section>

<%= image_tag 'blwr.png', style: 'position: absolute; bottom: 0; right: 0;' %>


  <div class ="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="bg">
          <center><h3 class="login-heading mb-4">New Blog</h3></center>
          <%= form_with scope: :blog, url: blogs_path, local: true do |form| %>


            <div class="form-label-group">
              <label for="inputEmail">Blog title</label>
              <%= form.text_field :title, class: 'form-control'%>
            </div>

            <div class="form-label-group">
              <label for="inputEmail">Blog photo</label><br>
              <%= form.file_field :blog_pics%>
            </div>

            <div class="form-label-group">
              <label for="inputPassword">Blog content</label>
              <%= form.text_area :text, class: 'form-control',  required: true %>
            </div>

            <br>

            <%= form.submit "Save blog", class: 'btn btn-lg btn-block btn-login text-uppercase font-weight-bold mb-2' %>

            <div class="text-center">
            <%= link_to 'BACK', root_path, class: 'large', style: 'color: black; font-weight: 600; text-decoration: underline' %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</section>  































<!-- <h2>Write a blog</h2>

<%= form_with scope: :blog, url: blogs_path, local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %> -->

app/views/blogs/show.html.erb
<style>

</style>



<br><br><br><br>

<center>
  <div class="btn-group" role="group">
    <% if @blog.user == current_user %>
      <button type="button" class="btn btn-sm">
        <%= link_to 'WRITE NEW BLOG', new_blog_path, class: 'btn btn-sm btn-primary' %> &nbsp &nbsp
      </button>

      <button type="button" class="btn">
        <%= link_to 'EDIT BLOG', edit_blog_path, class: 'btn btn-sm btn-info' %> &nbsp &nbsp
      </button>

      <button type="button" class="btn">
        <%= link_to 'DELETE BLOG', blog_path, class: 'btn btn-sm btn-danger',
            method: :delete,
            data: { confirm: 'Are you sure? Once you delete you can no longer retrieve your blog' } %>
      </button>
    <% end %>
  </div>
  <hr>
</center>


<section>
  <div class="container">

      <% if @blog.blog_pics.attached? %>
        <%= image_tag @blog.blog_pics, class: 'card-img-top', style: 'width: 100px;' %>
      <% else %>
        <%= image_tag 'welcome.png', class: 'card-img-top', style: 'width: 100px;' %>
      <% end %>

        <h1 style="text-transform: uppercase; margin-top: 1em; font-weight: 600;"><%= @blog.title %></h1>
        <h6 class=" mt-2 text-muted" style="text-align: start;" >
          <%= "- #{@blog.user.username}" %>  
          
          <% if @blog.user.avatar.attached? %>
            <%=  image_tag @blog.user.avatar, style: 'border-radius: 50%; border: 1px solid grey; width: 30px;' %>
          <% else %>
            <%=  image_tag 'profile.png', style: 'border-radius: 50%; width: 30px;' %>
          <% end %>
        </h6>

        <p style="margin-top: 2em; font-size: 1.5rem; text-align: justify; color: #5c5c5b;"><%= @blog.text %></p>

        <center style="margin-top: 10em; margin-bottom: 3em; font-size: 1.2rem;"><%= link_to 'BACK', root_path %></center>

  </div>
</section>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" style="margin-top: 60px; margin-bottom: 0; z-index: 1000;">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <% if value.class == Hash %>
            <% value.each do |k, v| %>
              <%= k %>
              <%= v %>
            <% end %>
          <% else %>
            <%= value %>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bloggers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
   

    <style>
      html{
        overflow-x: hidden;
        height: 100%;
        scroll-behavior: smooth;
      }
      body{
        overflow-x: hidden
        height: 100%;
        font-family: "Poppins", Arial, sans-serif;
      }

      .s1, .s2{
          display: none;
      }

      @media (max-width: 768px){
        .s1, .s2{
          display: block;
        }

        .s3, .s4{
          display: none;
        }
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#" style="font-weight: 700;">BLOGGERS</a>
    <% if !current_user %>
      <%= link_to "Sign Up", new_user_registration_path, class: 's1 btn btn-sm btn-info navbar-item' %> &nbsp
      <%= link_to "Sign In", user_session_path, class: 's2 btn btn-sm btn-info navbar-item'  %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Write Blog', new_blog_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if current_user %>
            <%= link_to 'Account Settings', edit_user_registration_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
      <span class="navbar-text">
        <% if current_user %>
          <%= "Logged in as #{current_user.username} " %>
          <% if current_user.avatar.attached? %>
            <%=  image_tag current_user.avatar, style: 'border-radius: 50%; border: 1px solid grey; width: 40px;' %>
          <% else %>
            <%=  image_tag 'profile.png', style: 'border-radius: 50%; width: 40px;' %>
          <% end %> 
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-warning', style: 'color: white;' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: 's3 btn btn-sm btn-info navbar-item' %> &nbsp
          <%= link_to "Sign In", user_session_path, class: 's4 btn btn-sm btn-info navbar-item'  %>
        <% end %>
      </span>
    </div>
  </nav>




  <!-- <div style="position: absolute; top: 5%;">
    <p class="notice" ><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
  </div> -->


  <%= render 'layouts/messages' %>



    <%= yield %>




  </body>
</html>

app/views/welcome/index.html.erb
<style>
  .land{
    height: 100vh;
    background-image: linear-gradient(to bottom right, #ffe259, #ffa751);
  }
  .land .box{
    position: absolute;
    left: 10em;
    top: 10em;
    z-index: 200;
  }
  .land img{
    position: absolute;
    bottom: 0;
    right: 0;    
  }

  .card{
    margin-top: 2em;
    margin-bottom: 2em;
  }

  .card-img-top{
    object-fit: contain;
    margin-right: auto;
    margin-left: auto;
  }

  .card-title{
    text-align: start;
    font-size: 1.5rem;
    text-transform: uppercase;
    font-weight: 600;
  }

  .lincard{
    color: unset;
    text-decoration: unset;
  }
  .lincard:hover{
    color: #5c5c5b;
    text-decoration: unset;
  }



  @media (max-width: 768px){
    .land .box{
      font-size: 0.1em;
      top: 60em;
    }

    .land img{
      width: 700px
    }
  }
</style>

<div class="land">
  <div class="box">
    <h1> Hello! Welcome to</h1>
    <h1>Bloggers</h1>

    <br><br>
    <%= link_to 'Write Blog', new_blog_path, class: "btn btn-md btn-primary" %> &nbsp
    <a href="#sec" class="btn btn-md btn-primary">View Blogs &#8595;</a>
  </div>

  <%= image_tag 'land.png' %>
</div>

<section id="sec" class="container">
  <% @blogs.each do |blog| %>
    <div class="row">
      <div class="col-md-3"></div>
        <div class="col-md-6">
          <center>
            <div class="card">
            <%= link_to blog_path(blog), class: "lincard" do %>

              <% if blog.blog_pics.attached? %>
                <%= image_tag blog.blog_pics, class: 'card-img-top' %>
                <% else %>
                <%= image_tag 'welcome.png', class: 'card-img-top' %>
              <% end %>

                <hr style="margin: 0;">

                <div class="card-body">
                  <h5 class="card-title"><%= blog.title %></h5>

                  <h6 class="card-subtitle mt-2 text-muted" style="text-align: end;" >
                    <%= "- #{blog.user.username}" %>

                    <% if blog.user.avatar.attached? %>
                      <%=  image_tag blog.user.avatar, style: 'border-radius: 50%; border: 1px solid grey; width: 30px;' %>
                    <% else %>
                      <%=  image_tag 'profile.png', style: 'border-radius: 50%; width: 30px;' %>
                    <% end %>
                  </h6>
                </div>
              <% end %>
            </div>
          </center>
        </div>
      <div class="col-md-3"></div>
    </div>
  <% end %>
</section>